spring:
  application:
    name: BANK AUTHORIZE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb
    password: password
  h2:
    console:
      enabled: 'true'
      path: /h2-console
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    path: /
bank-authorize-swagger:
  server:
    url: /
    description: API BANK AUTHORIZE
  info:
    title: BANK AUTHORIZE
    description: Technical Challenge Project
    version: Versão Beta
    contact:
      name: Rodolfo Gonçalves de Luna Freire
      url: https://www.linkedin.com/in/rodolfo-goncalves-luna-freire/
      email: rodolfod2r2@gmail.com
    termsOfServiceUrl: https://rodolfod2r2.medium.com/terms/service/protect/
    license: Apache License User
    licenseUrl: https://rodolfod2r2.medium.com/licenses/LICENSE-2.0.html
management:
  endpoints:
    web:
      exposure:
        include: '*'
